# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Lab Manual - Data Analysis and Visualisation - Class IX
author: Bhartiya Shiksha Board
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/amita-kapoor/BSB  # Online location of your book
  path_to_book: "."  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  notebook_interface: "jupyterlab"
  binderhub_url: "https://mybinder.org"
  thebe: true

thebe:
  repository_url: https://github.com/amita-kapoor/BSB
  repository_branch: main
  path_to_book: "."


# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  extra_footer: |
    <script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js"></script>
    <script>
      // This config helps the browser find the right version if automatic loading fails
      window.requirejs.config({
        map: {
          '*': {
            '@jupyter-widgets/base': 'https://cdn.jsdelivr.net/npm/@jupyter-widgets/base@6',
            '@jupyter-widgets/controls': 'https://cdn.jsdelivr.net/npm/@jupyter-widgets/controls@5',
            '@jupyter-widgets/output': 'https://cdn.jsdelivr.net/npm/@jupyter-widgets/output@6'
          }
        }
      });
    </script>
    <script src="https://cdn.jsdelivr.net/npm/@jupyter-widgets/html-manager@1.0.10/dist/embed-amd.js"></script>

  extra_head: |
    <script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js"></script>
    <script src="https://unpkg.com/@jupyter-widgets/html-manager@^1.0.1/dist/embed-amd.js"></script>

